apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xxl-mq.fullname" . }}
  labels:
    {{- include "xxl-mq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xxl-mq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xxl-mq.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xxl-mq.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PARAMS
              value: {{ .Values.global.params }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if not .Values.global.volume.enable }}
          volumeMounts:
            - name: {{ include "xxl-mq.fullname" . }}-data-volume
              mountPath: {{ .Values.global.volume.mountPath }}
          {{- end }}
        {{- if not .Values.global.volume.enable }}
        volumes:
          - name: {{ include "xxl-mq.fullname" . }}-data-volume
            persistentVolumeClaim:
              claimName: {{ include "xxl-mq.fullname" . }}-mq-data-volume
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
